### ISSUE TITLE
`allowOutsideClick: false` no longer works

### ISSUE THREAD

**Issue by SnidelyWhiplash** [t4t5/sweetalert#320]
Looks like https://github.com/t4t5/sweetalert/commit/7720ccafea1a259165207ee9842da11c770f6420 actually removed the ability to prevent outside clicks.

Also note the typo in the data attribute (`data-allow-ouside-click`) both where it's set and read.

**Comment by cordoval** [comment]
any change please to get #320 merged and tag a new release even a lesser version number :shipit:

**Comment by t4t5** [comment]
This should be fixed in v1.0.0-beta (`bower install sweetalert#1.0.0-beta`). Make sure you check the release notes to update the file locations! https://github.com/t4t5/sweetalert/releases/tag/v1.0.0-beta

**Comment by michalzubkowicz** [comment]
It's not fully fixed, It's still possible on very beginning of initialization (on double click of button etc)
