### ISSUE TITLE
the latest version cannot work in ng2+, npm install result is not complete

### ISSUE THREAD

**Issue by xmeng1** [t4t5/sweetalert#738]
The last version 'npm install' the package in `node_modules` is not complete:
**version 2.0.4**
![selection_041](https://user-images.githubusercontent.com/5753142/31174271-d24e69fe-a902-11e7-93e6-d992109b74dc.png)

**version 2.0.3**
![selection_042](https://user-images.githubusercontent.com/5753142/31174277-d61dd68c-a902-11e7-8bd1-f0ba77d2d663.png)

So with the latest version in Angular2+, the `swal` cannot be found and imported.

**Comment by t4t5** [comment]
The `src` folder should not be necessary for using SweetAlert. When you use `import swal from 'sweetalert'` it should pull the file from the `dist` folder. Are you sure it doesn't work when you try?

**Comment by xmeng1** [comment]
I have tried use angular CLI 1.3.2 to create a clean project and npm install the latest of sweetalert. I cannot import swal and error has been displayed in the picture (after change to 2.0.3, the error was gone)

**Comment by t4t5** [comment]
It shouldn't matter which Angular version you use since SweetAlert just uses simple ES imports. I don't see any error in your screenshots so I'm going to go ahead and close this.

**Comment by xmeng1** [comment]
![selection_043](https://user-images.githubusercontent.com/5753142/31178162-220971fc-a910-11e7-946f-15b8850f5245.png)

**Comment by t4t5** [comment]
Thanks, I see the problem now. Will investigate!

**Comment by xmeng1** [comment]
OK thanks

**Comment by t4t5** [comment]
Alright, I just published v2.0.5 on NPM. Try to download that and try again. Also, make sure that you add the following line in your project's `tsconfig.json`:

```json
    "allowSyntheticDefaultImports": true,
```

**Comment by xmeng1** [comment]
Thanks. I have tried it
If I import swal as follow:
```
import * as swal from 'sweetalert';
```
it works perfect.

But if I import it as previous:
```
import swal from 'sweetalert';
```
There is still an error as follows, I think the sweetalert.d.ts should export default class swal, then the swal can be imported directly according to this https://github.com/Microsoft/TypeScript/issues/3337
![image](https://user-images.githubusercontent.com/5753142/31182055-c29d9210-a91a-11e7-9a75-87272f82fcdd.png)

**Comment by Safo91** [comment]
same issue as @xmeng1 , only import as works

**Comment by xmeng1** [comment]
change `sweetalert.d.ts` to this code, then `swal` can be imported directly

//export = swal;
export as namespace swal;
export default swal;

**Comment by andyfrontend** [comment]
Same here :(
